apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  selector:
    app: synergychat-api
    type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  #   nodePort: 30080
